import type { Product, Category, Order, Offer } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Men's Clothing",
    description: "Stylish and comfortable clothing for men",
    image: "/mens-clothing-fashion.jpg",
    subcategories: ["Shirts", "T-Shirts", "Pants", "Jeans", "Jackets", "Suits"],
  },
  {
    id: "2",
    name: "Women's Clothing",
    description: "Elegant and trendy clothing for women",
    image: "/womens-clothing-fashion.jpg",
    subcategories: ["Dresses", "Tops", "Skirts", "Pants", "Jackets", "Blouses"],
  },
  {
    id: "3",
    name: "Kids' Clothing",
    description: "Fun and comfortable clothing for children",
    image: "/kids-clothing-fashion.jpg",
    subcategories: ["Boys", "Girls", "Baby", "School Uniforms"],
  },
  {
    id: "4",
    name: "Accessories",
    description: "Complete your look with our accessories",
    image: "/fashion-accessories-collection.png",
    subcategories: ["Bags", "Belts", "Hats", "Scarves", "Jewelry"],
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Cotton Shirt",
    description: "High-quality cotton shirt perfect for formal and casual occasions",
    price: 2500,
    originalPrice: 3000,
    category: "Men's Clothing",
    subcategory: "Shirts",
    images: ["/premium-cotton-shirt-mens.jpg", "/cotton-shirt-back-view.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Blue", "Black", "Gray"],
    inStock: true,
    featured: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Elegant Summer Dress",
    description: "Beautiful floral summer dress made from breathable fabric",
    price: 3500,
    category: "Women's Clothing",
    subcategory: "Dresses",
    images: ["/elegant-summer-dress-floral.jpg", "/summer-dress-side-view.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Blue", "Floral Pink", "Solid White"],
    inStock: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    name: "Kids Fun T-Shirt",
    description: "Colorful and comfortable t-shirt for active kids",
    price: 1200,
    category: "Kids' Clothing",
    subcategory: "Boys",
    images: ["/kids-colorful-t-shirt-cartoon.jpg"],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Red", "Blue", "Green", "Yellow"],
    inStock: true,
    featured: false,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "4",
    name: "Leather Handbag",
    description: "Stylish leather handbag perfect for everyday use",
    price: 4500,
    originalPrice: 5500,
    category: "Accessories",
    subcategory: "Bags",
    images: ["/leather-handbag-brown-elegant.jpg"],
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
    inStock: true,
    featured: true,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "5",
    name: "Casual Denim Jeans",
    description: "Comfortable slim-fit denim jeans for everyday wear",
    price: 2800,
    category: "Men's Clothing",
    subcategory: "Jeans",
    images: ["/casual-denim-jeans-mens-blue.jpg"],
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Dark Blue", "Light Blue", "Black"],
    inStock: true,
    featured: false,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "6",
    name: "Office Blazer",
    description: "Professional blazer perfect for business meetings",
    price: 5500,
    category: "Women's Clothing",
    subcategory: "Jackets",
    images: ["/office-blazer-womens-professional.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black", "Gray"],
    inStock: true,
    featured: true,
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-11"),
  },
]

export const orders: Order[] = [
  {
    id: "ORD-001",
    customerName: "John Doe",
    customerEmail: "john@example.com",
    customerPhone: "+94771234567",
    items: [
      {
        productId: "1",
        name: "Premium Cotton Shirt",
        price: 2500,
        image: "/cotton-shirt.png",
        size: "L",
        color: "Blue",
        quantity: 2,
      },
    ],
    total: 5000,
    status: "processing",
    createdAt: new Date("2024-01-16"),
    shippingAddress: {
      street: "123 Main Street",
      city: "Colombo",
      state: "Western",
      zipCode: "00100",
      country: "Sri Lanka",
    },
  },
]

export const offers: Offer[] = [
  {
    id: "1",
    title: "New Year Sale",
    description: "Get 20% off on all items",
    discountType: "percentage",
    discountValue: 20,
    minOrderValue: 2000,
    validFrom: new Date("2024-01-01"),
    validTo: new Date("2024-01-31"),
    isActive: true,
    applicableCategories: ["Men's Clothing", "Women's Clothing"],
  },
  {
    id: "2",
    title: "Free Shipping",
    description: "Free shipping on orders above Rs. 3000",
    discountType: "fixed",
    discountValue: 500,
    minOrderValue: 3000,
    validFrom: new Date("2024-01-15"),
    validTo: new Date("2024-02-15"),
    isActive: true,
  },
]
